name: Github CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: "psarcjs test"
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: run test script
      run: |
        sudo apt-get install libmagick++-dev
        pip3 install --upgrade pip
        pip3 install git+https://github.com/0x0L/rocksmith.git
        npm install
        npm run build
        npm run test
        npm run cover
